DB_POOL_PRE_PING_ENV = "DB_POOL_PRE_PING"
DB_POOL_PRE_PING_DEFAULT_ENV = "DB_POOL_PRE_PING_DEFAULT"

DB_POOL_RECYCLE_SECONDS_ENV = "DB_POOL_RECYCLE_SECONDS"
DB_POOL_RECYCLE_SECONDS_DEFAULT_ENV = "DB_POOL_RECYCLE_SECONDS_DEFAULT"
DB_POOL_RECYCLE_SECONDS_MIN_ENV = "DB_POOL_RECYCLE_SECONDS_MIN"

DB_POOL_SIZE_ENV = "DB_POOL_SIZE"
DB_POOL_SIZE_DEFAULT_ENV = "DB_POOL_SIZE_DEFAULT"
DB_POOL_SIZE_MIN_ENV = "DB_POOL_SIZE_MIN"

DB_POOL_MAX_OVERFLOW_ENV = "DB_POOL_MAX_OVERFLOW"
DB_POOL_MAX_OVERFLOW_DEFAULT_ENV = "DB_POOL_MAX_OVERFLOW_DEFAULT"
DB_POOL_MAX_OVERFLOW_MIN_ENV = "DB_POOL_MAX_OVERFLOW_MIN"

DB_POOL_TIMEOUT_SECONDS_ENV = "DB_POOL_TIMEOUT_SECONDS"
DB_POOL_TIMEOUT_SECONDS_DEFAULT_ENV = "DB_POOL_TIMEOUT_SECONDS_DEFAULT"
DB_POOL_TIMEOUT_SECONDS_MIN_ENV = "DB_POOL_TIMEOUT_SECONDS_MIN"