from __future__ import annotations

ROLE_PLATFORM_ADMIN = "Platform Admin"
ROLE_MASTER_ADMIN = "Master Admin"
ROLE_SUPER_ADMIN = "Super Admin"
ROLE_AGENT_OWNER = "Agent Owner"
ROLE_SECURITY_APPROVER = "Security Approver"
ROLE_AI_OPS_APPROVER = "AI Ops Approver"
ROLE_RELEASE_MANAGER = "Release Manager"
ROLE_AUDITOR = "Auditor"

SUPPORTED_ACTOR_ROLES = {
	ROLE_MASTER_ADMIN,
	ROLE_SUPER_ADMIN,
	ROLE_PLATFORM_ADMIN,
	ROLE_AGENT_OWNER,
	ROLE_SECURITY_APPROVER,
	ROLE_AI_OPS_APPROVER,
	ROLE_RELEASE_MANAGER,
	ROLE_AUDITOR,
}

AUTH_SESSION_READ_ROLES_DEFAULT = {
	ROLE_MASTER_ADMIN,
	ROLE_PLATFORM_ADMIN,
	ROLE_SECURITY_APPROVER,
	ROLE_AUDITOR,
}

AUTH_SESSION_ISSUER_ROLES_DEFAULT = {
	ROLE_MASTER_ADMIN,
	ROLE_PLATFORM_ADMIN,
	ROLE_RELEASE_MANAGER,
}

ISSUABLE_SESSION_ROLES_DEFAULT = set(SUPPORTED_ACTOR_ROLES)

CROSS_ACTOR_DUAL_APPROVAL_ROLES_DEFAULT = {
	ROLE_MASTER_ADMIN,
	ROLE_PLATFORM_ADMIN,
	ROLE_SECURITY_APPROVER,
	ROLE_RELEASE_MANAGER,
}

DUAL_APPROVAL_REQUIRED_APPROVER_ROLE_DEFAULT = ROLE_SECURITY_APPROVER

PRIVILEGED_MFA_REAUTH_MINUTES_DEFAULT = 15

DEFAULT_BASIC_AUTH_MAX_ENABLE_DURATION_MINUTES = 60
DEFAULT_BASIC_AUTH_ENABLE_DURATION_MINUTES = 30

DEFAULT_SESSION_TTL_MINUTES = 60
DEFAULT_SESSION_IDLE_TIMEOUT_MINUTES = 30

MIN_SESSION_TTL_MINUTES = 1
MAX_SESSION_TTL_MINUTES = 1440

MIN_SESSION_IDLE_TIMEOUT_MINUTES = 1
MAX_SESSION_IDLE_TIMEOUT_MINUTES = 720

AUTH_POLICY_DEFAULT_ID = "default"

COST_SCOPE_USER = "user"
COST_SCOPE_TEAM = "team"
COST_SCOPE_GROUP = "group"
COST_SCOPE_OWNER = "owner"
COST_SCOPE_ACTOR = "actor"
COST_SCOPE_AGENT = "agent"
COST_SCOPE_ENVIRONMENT = "environment"

SUPPORTED_BUDGET_SCOPE_TYPES = {
	COST_SCOPE_USER,
	COST_SCOPE_TEAM,
	COST_SCOPE_GROUP,
	COST_SCOPE_OWNER,
	COST_SCOPE_ACTOR,
	COST_SCOPE_AGENT,
	COST_SCOPE_ENVIRONMENT,
}

COST_POLICY_DECISION_ALLOW = "allow"
COST_POLICY_DECISION_WARN = "warn"
COST_POLICY_DECISION_DENY = "deny"
