from app.policy_constants import (
    ROLE_AGENT_OWNER,
    ROLE_AI_OPS_APPROVER,
    ROLE_AUDITOR,
    ROLE_PLATFORM_ADMIN,
    ROLE_RELEASE_MANAGER,
    ROLE_SECURITY_APPROVER,
    ROLE_SUPER_ADMIN,
)

PLATFORM_ADMIN_EQUIVALENT_ROLES = {ROLE_PLATFORM_ADMIN, ROLE_SUPER_ADMIN}

# Shared router authorization sets
AUTH_ADMIN_ROLES = set(PLATFORM_ADMIN_EQUIVALENT_ROLES)
AUTH_SESSION_REAUTH_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_RELEASE_MANAGER, ROLE_SECURITY_APPROVER}
AUTH_ADMIN_OR_SECURITY_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_SECURITY_APPROVER}
AUTH_POLICY_REVISIONS_DEFAULT_LIMIT = 50

GATEWAY_READ_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_SECURITY_APPROVER, ROLE_AUDITOR}
GATEWAY_ADMIN_ROLES = set(PLATFORM_ADMIN_EQUIVALENT_ROLES)
GATEWAY_ADMIN_OR_AI_OPS_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AI_OPS_APPROVER}
GATEWAY_ADMIN_OR_SECURITY_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_SECURITY_APPROVER}

PROVIDERS_ADMIN_ROLES = set(PLATFORM_ADMIN_EQUIVALENT_ROLES)
PROVIDERS_ADMIN_SECURITY_RELEASE_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_SECURITY_APPROVER, ROLE_RELEASE_MANAGER}
PROVIDERS_ADMIN_SECURITY_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_SECURITY_APPROVER}
PROVIDERS_ADMIN_SECURITY_AUDITOR_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_SECURITY_APPROVER, ROLE_AUDITOR}

OWNER_WRITE_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AGENT_OWNER}
OWNER_READ_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AUDITOR, ROLE_AGENT_OWNER}
AUDIT_READ_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AUDITOR, ROLE_AGENT_OWNER}

DISCOVERY_READ_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AUDITOR}
DISCOVERY_WRITE_ROLES = set(PLATFORM_ADMIN_EQUIVALENT_ROLES)
COMPLIANCE_READ_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AUDITOR}
COMPLIANCE_WRITE_ROLES = set(PLATFORM_ADMIN_EQUIVALENT_ROLES)

ROLES_PLAYGROUND_WRITE = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AGENT_OWNER, ROLE_AI_OPS_APPROVER}
ROLES_PLAYGROUND_READ = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AGENT_OWNER, ROLE_AI_OPS_APPROVER, ROLE_SECURITY_APPROVER}
ROLES_BENCHMARK_SCAN_WRITE = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AGENT_OWNER, ROLE_AI_OPS_APPROVER}
ROLES_BENCHMARK_SCAN_READ = ROLES_BENCHMARK_SCAN_WRITE | {ROLE_RELEASE_MANAGER, ROLE_SECURITY_APPROVER, ROLE_AUDITOR}

ROLES_ROUTE_DRAFT_SUBMIT = {ROLE_AGENT_OWNER, ROLE_AI_OPS_APPROVER}
ROLES_ROUTE_DRAFT_APPROVE = {ROLE_SECURITY_APPROVER, ROLE_AI_OPS_APPROVER}
ROLES_ROUTE_DRAFT_REJECT = {ROLE_SECURITY_APPROVER, ROLE_AI_OPS_APPROVER, ROLE_RELEASE_MANAGER}
ROLES_ROUTE_DRAFT_RELEASE = {ROLE_RELEASE_MANAGER}
ROLES_ROUTE_DRAFT_ROLLBACK = {ROLE_RELEASE_MANAGER, ROLE_SECURITY_APPROVER, ROLE_AI_OPS_APPROVER}
ROLES_ROUTE_DRAFT_READ = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_RELEASE_MANAGER, ROLE_AUDITOR, ROLE_AGENT_OWNER}

ROLES_OBSERVABILITY_READ = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AUDITOR, ROLE_AGENT_OWNER}
ROLES_OBSERVABILITY_SCHEMA = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AUDITOR}

ROLES_ADMIN_RELEASE = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_RELEASE_MANAGER}
ROLES_ADMIN_RELEASE_AUDITOR = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_RELEASE_MANAGER, ROLE_AUDITOR}
ROLES_ADMIN_RELEASE_OWNER = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_RELEASE_MANAGER, ROLE_AGENT_OWNER}
ROLES_ADMIN_RELEASE_OWNER_AUDITOR = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_RELEASE_MANAGER, ROLE_AGENT_OWNER, ROLE_AUDITOR}
ROLES_ADMIN_RELEASE_AUDITOR_SECURITY_AIOPS = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_RELEASE_MANAGER, ROLE_AUDITOR, ROLE_SECURITY_APPROVER, ROLE_AI_OPS_APPROVER}
ROLES_SECURITY_AIOPS = {ROLE_SECURITY_APPROVER, ROLE_AI_OPS_APPROVER}
ROLES_ADMIN_OWNER = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AGENT_OWNER}

# Module router constants
REVIEW_REQUIRED_MODULE_TYPES = {"runtime", "gateway", "security"}
SUPPORTED_MODULE_PERMISSIONS = {
    "tools.read",
    "tools.execute",
    "models.invoke",
    "cache.read",
    "cache.write",
    "observability.emit",
    "secrets.read",
    "secrets.write",
    "gateway.route.update",
    "identity.federation.assume",
}
AGENT_OWNER_BLOCKED_PERMISSIONS = {
    "secrets.write",
    "gateway.route.update",
    "identity.federation.assume",
}
MODULE_READ_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AGENT_OWNER, ROLE_AUDITOR}
MODULE_WRITE_ROLES = PLATFORM_ADMIN_EQUIVALENT_ROLES | {ROLE_AGENT_OWNER}
MODULE_ADMIN_ROLES = set(PLATFORM_ADMIN_EQUIVALENT_ROLES)
