# Runtime configuration keys backed by database where available.

RUNTIME_CONFIG_GATEWAY_DEFAULT_GLOBAL_TIMEOUT_MS = "gateway.default_global_timeout_ms"
RUNTIME_CONFIG_GATEWAY_DEFAULT_MAX_FALLBACK_HOPS = "gateway.default_max_fallback_hops"
RUNTIME_CONFIG_GATEWAY_MCP_SERVERS_JSON = "gateway.mcp.servers_json"
RUNTIME_CONFIG_GATEWAY_MCP_DEFAULT_TIMEOUT_SECONDS = "gateway.mcp.default_timeout_seconds"
RUNTIME_CONFIG_GATEWAY_EXTERNAL_CALLBACKS_JSON = "gateway.external_callbacks_json"
RUNTIME_CONFIG_COST_MODEL_TOKEN_RATES_JSON = "cost.model_token_rates_json"
RUNTIME_CONFIG_COST_CLOUD_COMPONENT_MULTIPLIERS_JSON = "cost.cloud_component_multipliers_json"
RUNTIME_CONFIG_COST_PROVIDER_DISCOUNTS_JSON = "cost.provider_discounts_json"

RUNTIME_CONFIG_WORKLOAD_IDENTITY_EXPIRES_IN_SECONDS = "workload_identity.default_expires_in_seconds"
RUNTIME_CONFIG_WORKLOAD_IDENTITY_HTTP_TIMEOUT_SECONDS = "workload_identity.default_http_timeout_seconds"
RUNTIME_CONFIG_WORKLOAD_IDENTITY_EXPOSE_ACCESS_TOKEN = "workload_identity.expose_access_token"
RUNTIME_CONFIG_RATE_LIMIT_EXACT_RULES_JSON = "rate_limit.rules_exact_json"
RUNTIME_CONFIG_RATE_LIMIT_WILDCARD_RULES_JSON = "rate_limit.rules_wildcard_json"
RUNTIME_CONFIG_RATE_LIMIT_RULES_REFRESH_SECONDS = "rate_limit.rules_refresh_seconds"
RUNTIME_CONFIG_AUTH_POLICY_REVISIONS_DEFAULT_LIMIT = "auth.policy.revisions_default_limit"
RUNTIME_CONFIG_AUTH_LOGIN_MAX_FAILED_ATTEMPTS = "auth.login.max_failed_attempts"
RUNTIME_CONFIG_AUTH_LOGIN_LOCKOUT_MINUTES = "auth.login.lockout_minutes"
RUNTIME_CONFIG_SECURITY_CORS_ALLOW_ORIGINS_CSV = "security.cors_allow_origins_csv"
RUNTIME_CONFIG_COMPLIANCE_CONTROL_CATALOG_JSON = "compliance.control_catalog_json"
RUNTIME_CONFIG_COMPLIANCE_DEFAULT_CONTROL_MAPPINGS_JSON = "compliance.default_control_mappings_json"
RUNTIME_CONFIG_OBSERVABILITY_LOGS_DEFAULT_LIMIT = "observability.logs.default_limit"
RUNTIME_CONFIG_OBSERVABILITY_SCHEMA_DEFAULT_SAMPLE_SIZE = "observability.schema.default_sample_size"

RUNTIME_CONFIG_DEFAULTS: dict[str, str] = {
    RUNTIME_CONFIG_GATEWAY_DEFAULT_GLOBAL_TIMEOUT_MS: "4500",
    RUNTIME_CONFIG_GATEWAY_DEFAULT_MAX_FALLBACK_HOPS: "2",
    RUNTIME_CONFIG_GATEWAY_MCP_SERVERS_JSON: "[]",
    RUNTIME_CONFIG_GATEWAY_MCP_DEFAULT_TIMEOUT_SECONDS: "8.0",
    RUNTIME_CONFIG_GATEWAY_EXTERNAL_CALLBACKS_JSON: "[]",
    RUNTIME_CONFIG_COST_MODEL_TOKEN_RATES_JSON: '{"default":{"input_cents_per_1k":1.0,"output_cents_per_1k":2.0}}',
    RUNTIME_CONFIG_COST_CLOUD_COMPONENT_MULTIPLIERS_JSON: '{"provider_type":{"aws":1.0,"azure":1.0,"gcp":1.0,"openai":1.0,"anthropic":1.0},"endpoint_family":{"responses":1.0}}',
    RUNTIME_CONFIG_COST_PROVIDER_DISCOUNTS_JSON: '{"provider_type":{"aws":0.0,"azure":0.0,"gcp":0.0,"openai":0.0,"anthropic":0.0},"models":{}}',
    RUNTIME_CONFIG_WORKLOAD_IDENTITY_EXPIRES_IN_SECONDS: "3600",
    RUNTIME_CONFIG_WORKLOAD_IDENTITY_HTTP_TIMEOUT_SECONDS: "3.0",
    RUNTIME_CONFIG_WORKLOAD_IDENTITY_EXPOSE_ACCESS_TOKEN: "false",
    RUNTIME_CONFIG_RATE_LIMIT_RULES_REFRESH_SECONDS: "30",
    RUNTIME_CONFIG_AUTH_POLICY_REVISIONS_DEFAULT_LIMIT: "50",
    RUNTIME_CONFIG_AUTH_LOGIN_MAX_FAILED_ATTEMPTS: "5",
    RUNTIME_CONFIG_AUTH_LOGIN_LOCKOUT_MINUTES: "15",
    RUNTIME_CONFIG_OBSERVABILITY_LOGS_DEFAULT_LIMIT: "50",
    RUNTIME_CONFIG_OBSERVABILITY_SCHEMA_DEFAULT_SAMPLE_SIZE: "200",
}
